server:
  port: 8080
order.api:
  url: http://localhost:8081/
my:
  db:
    schemaname: site_api

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${my.db.schemaname}
    liquibase-schema: ${my.db.schemaname}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pgpwd4habr
    url: jdbc:postgresql://localhost:5432/onlineStorePortalNew?currentSchema=${my.db.schemaname}
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect